name: 'My Plugin'
description: 'Creates a check run'

runs:
  using: 'composite'
  steps:
    - name: Create check run
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "github.sha: ${{ github.sha }}"
        echo "pr.head.sha: ${{ github.event.pull_request.head.sha }}"
        curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d @- <<EOF
        {
          "name": "myplugin",
          "head_sha": "${{ github.event.pull_request.head.sha }}",
          "status": "completed",
          "conclusion": "success",
          "output": {
            "title": "myplugin",
            "summary": "hello this is my first custom plugin"
          }
        }
        EOF